### ISSUE TITLE
Could not find comment in relation hyperlink to source work item on target work item with id

### ISSUE THREAD

**Issue by ephos** [Microsoft/vsts-work-item-migrator#13]
When running the WiMigrator I am finding that validation passes, migration phase 1 passes, however phase 2 ends with the following unexpected error.

`Could not find comment in relation hyperlink to source work item on target work item with id: 5366. Expected source work item id: 216112`

I've tried a few different configuration changes in the _configuration.json_ like re-mapping some problematic fields but still seem to be getting the error.

**Comment by ephos** [comment]
Just for some additional information we created an entirely vanilla no customization CMMI workspace with a single backlog item and that item threw the same unexpected error.

**Comment by tbergstedt** [comment]
I am experiencing this error as well. For info, the full exception message is:

> [Error   @15.43.02.484] Unexpected error: System.Exception: Could not find comment in relation hyperlink to source work item on target work item with id: 552259. Expected source work item id: 512729
   at Common.Migration.Migrator.GetRevAndPhaseStatus(WorkItem targetWorkItem, Int32 sourceWorkItemId) in C:\tools\vsts-work-item-migrator\Common\Migration\Migrator.cs:line 273
   at Common.Migration.Migrator.GenerateWitBatchRequestsForPhase2Batch(IBatchMigrationContext batchContext, Int32 batchId, IList`1 workItemMigrationState, IList`1 sourceWorkItems, IList`1 targetWorkItems) in C:\tools\vsts-work-item-migrator\Common\Migration\Migrator.cs:line 204
   at Common.Migration.Migrator.<>c__DisplayClass8_0.<<MigratePhase2>b__2>d.MoveNext() in C:\tools\vsts-work-item-migrator\Common\Migration\Migrator.cs:line 101
--- End of stack trace from previous location where exception was thrown ---
   at TaskExtensions.<>c__DisplayClass0_1`1.<<ForEachAsync>b__1>d.MoveNext() in C:\tools\vsts-work-item-migrator\Common\Extensions\TaskExtensions.cs:line 22
--- End of stack trace from previous location where exception was thrown ---
   at Common.Migration.Migrator.MigratePhase2() in C:\tools\vsts-work-item-migrator\Common\Migration\Migrator.cs:line 84
   at Common.Migration.Migrator.Migrate() in C:\tools\vsts-work-item-migrator\Common\Migration\Migrator.cs:line 35
   at WiMigrator.CommandLine.ExecuteMigration(CommandOption migrate) in C:\tools\vsts-work-item-migrator\WiMigrator\CommandLine.cs:line 144. Could not find comment in relation hyperlink to source work item on target work item with id: 552259. Expected source work item id: 512729

When I previously tried the same operation in our test environment, using a backup of TFS production, I did not experience this. This leads me to think that it is more of a configuration/security issue; nevertheless, I would like some guidance on how to fix this.

**Comment by sferg-msft** [comment]
@tbergstedt Did you ever get around this issue?  The code you quoted above is not comparing the http/https portion, just the account name.  Could you share the URL you were getting?

**Comment by marncosta** [comment]
I am having the same issue. But I tried to change may code like quoted by tbergstedt and didnt´t work. Anyone got the resolution for this issue?
For my case, the code that is not working is: 
if (targetWorkItem.Relations != null)
            {
                foreach (WorkItemRelation relation in targetWorkItem.Relations)
                {
                    if (RelationHelpers.IsRelationHyperlinkToSourceWorkItem(context, relation, sourceWorkItemId))
                    {
                        // get the key even if its letter case is different but it matches otherwise
                        string keyFromFields = relation.Attributes.GetKeyIgnoringCase(Constants.RelationAttributeComment);
                        string relationRevAndPhaseStatusComment = relation.Attributes[keyFromFields].ToString();

                        RevAndPhaseStatus revAndPhaseStatus = new RevAndPhaseStatus(relationRevAndPhaseStatusComment);
                        return revAndPhaseStatus;
                    }
                }
            }
              throw new Exception($"Could not find comment in relation hyperlink to source work item on target work item with id: {targetWorkItem.Id.Value}. Expected source work item id: {sourceWorkItemId}");

**Comment by marncosta** [comment]
I have solved my  problem related to this exception: "Could not find comment in relation hyperlink to source work item on target work item with id: {targetWorkItem.Id.Value}. Expected source work item id: {sourceWorkItemId}")
 I didn´t insert **full qualified URL** on both source-connection/account and  target-connection/account properties in configuration.json. After, I updated for full qualified URL and It is ok.

**Comment by tbergstedt** [comment]
@sferg-msft Sorry, I am unable to reproduce the problem, due to the simple fact that we a while ago switched to https:// only for our TFS connections.
